version: "3.7"

services:
  camera:
    depends_on:
     - whip
    image: eyevinntechnology/ffmpeg-base:0.3.0
    network_mode: "host"
    command: [ "ffmpeg", "-fflags", "nobuffer", "-rtsp_transport", "tcp", "-i", "<RTSP_INPUT>", "-vcodec", "copy", "-acodec", "aac", "-f", "mpegts", "udp://127.0.0.1:9998?pkt_size=1316" ]
  whipclient:
    build: .
    image: mpegts-whip:dev
    network_mode: "host"
    command: [ "./mpeg-ts-client", "-a", "0.0.0.0", "-p", "9998", "-u", "<WHIP_ENDPOINT>" ]

